# Generated by Django 5.1.6 on 2025-04-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0003_merge_0002_add_author_fields_XXXX_fix_author_fields"),
    ]

    operations = []
