# Generated by Django 5.1.6 on 2025-05-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20230401_1200'),  # Update to depend on 0005 instead of 0006
    ]

    operations = []
