# Generated by Django 5.1.6 on 2025-05-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0008_convert_publication_years_to_strings"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="affiliation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="researchpaper",
            name="methodology_type",
            field=models.CharField(blank=True, default="Unknown", max_length=50),
        ),
        migrations.AlterField(
            model_name="researchpaper",
            name="publication_year",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Publication Year"
            ),
        ),
    ]
