# Generated by Django 5.1.6 on 2025-05-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0009_author_affiliation_author_email_and_more"),
    ]

    operations = []
