# Generated by Django 5.1.6 on 2025-06-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0010_auto_20230401_1200"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="year_created",
            field=models.CharField(
                blank=True,
                help_text="Year when the author was added",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="year_updated",
            field=models.CharField(
                blank=True,
                help_text="Year when the author was last updated",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="keyword",
            name="year_created",
            field=models.CharField(
                blank=True,
                help_text="Year when the keyword was added",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="keyword",
            name="year_updated",
            field=models.CharField(
                blank=True,
                help_text="Year when the keyword was last updated",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="researchpaper",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="papers", to="research.author"
            ),
        ),
    ]
