# Generated by Django 5.1.6 on 2025-06-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0011_author_year_created_author_year_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='year_created',
            field=models.CharField(blank=True, help_text='Year when the keyword was added', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='year_updated',
            field=models.CharField(blank=True, help_text='Year when the keyword was last updated', max_length=4, null=True),
        ),
    ]
