# Generated by Django 5.1.6 on 2025-06-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0014_alter_keyword_field_types"),
    ]

    operations = [
        # Remove the AddField operation since created_at already exists
        # Just use a no-op operation to mark this migration as applied
        migrations.RunPython(
            code=lambda apps, schema_editor: None,
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]
