# Generated by Django 5.1.6 on 2025-06-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0015_keyword_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="keyword",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
