# Generated by Django 5.1.6 on 2025-06-29 12:28

from django.db import migrations, models


def check_and_alter_fields(apps, schema_editor):
    """Check if fields exist and alter them if needed"""
    from django.db import connection

    with connection.cursor() as cursor:
        # Check and alter created_at field
        cursor.execute(
            """
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'research_author' AND column_name = 'created_at'
        """
        )
        if cursor.fetchone():
            cursor.execute(
                """
                ALTER TABLE research_author 
                ALTER COLUMN created_at DROP NOT NULL
            """
            )
        
        # Check and alter updated_at field
        cursor.execute(
            """
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'research_author' AND column_name = 'updated_at'
        """
        )
        if cursor.fetchone():
            cursor.execute(
                """
                ALTER TABLE research_author 
                ALTER COLUMN updated_at DROP NOT NULL
            """
            )


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0016_author_created_at_keyword_created_at"),
    ]

    operations = [
        migrations.RunPython(check_and_alter_fields, migrations.RunPython.noop),
    ]
