# Generated by Django 5.1.6 on 2025-07-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0018_alter_author_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="researchpaper",
            options={
                "ordering": ["-publication_year", "-created_at", "id"],
                "verbose_name": "Research Paper",
                "verbose_name_plural": "Research Papers",
            },
        ),
        migrations.AlterField(
            model_name="author",
            name="affiliation",
            field=models.CharField(max_length=255),
        ),
    ]
