[phases.build]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt",
  "python manage.py collectstatic --noinput"
]

[phases.deploy]
cmds = ["python manage.py migrate --noinput"]

[variables]
PYTHONPATH = "/app"
DJANGO_SETTINGS_MODULE = "core.settings"
