[phases.build]
cmds = [
  "python manage.py migrate --noinput",
  "python manage.py collectstatic --noinput"
]

[phases.start]
cmd = "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"

[variables]
PYTHONPATH = "/app"
DJANGO_SETTINGS_MODULE = "core.settings"
PORT = "8000"

[nixpkgs]
packages = [
  "pangocairo",
  "pango",
  "cairo",
  "pkg-config",
  "glib",
  "freetype",
  "fontconfig"
]
  
