# Generated by Django 5.1.6 on 2025-04-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_populate_keyword_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={},
        ),
        migrations.AlterModelOptions(
            name="keyword",
            options={},
        ),
        migrations.AlterModelOptions(
            name="keywordcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Keyword Category",
                "verbose_name_plural": "Keyword Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="researchpaper",
            options={},
        ),
        migrations.RemoveField(
            model_name="keyword",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="researchpaper",
            name="external_url",
        ),
        migrations.RemoveField(
            model_name="researchpaper",
            name="pdf_file",
        ),
        migrations.AddField(
            model_name="researchpaper",
            name="download_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="researchpaper",
            name="slug",
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category this keyword belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="keywords",
                to="research.keywordcategory",
            ),
        ),
        migrations.AlterField(
            model_name="keywordcategory",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of what this category represents"
            ),
        ),
        migrations.AlterField(
            model_name="keywordcategory",
            name="name",
            field=models.CharField(
                help_text="Name of the keyword category", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="researchpaper",
            name="citation_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="researchpaper",
            name="citation_trend",
            field=models.CharField(
                choices=[
                    ("increasing", "Increasing"),
                    ("stable", "Stable"),
                    ("decreasing", "Decreasing"),
                ],
                default="stable",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="researchpaper",
            name="doi",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="researchpaper",
            name="keywords",
            field=models.ManyToManyField(related_name="papers", to="research.keyword"),
        ),
        migrations.AlterField(
            model_name="researchpaper",
            name="methodology_type",
            field=models.CharField(
                choices=[
                    ("qualitative", "Qualitative"),
                    ("quantitative", "Quantitative"),
                    ("mixed", "Mixed Methods"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="author",
            unique_together={("name", "affiliation")},
        ),
    ]
