# Generated by Django 5.1.6 on 2025-04-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_forumpost_likes_count"),
        ("forum", "add_guest_fields"),
    ]

    operations = []
