# Generated by Django 5.1.6 on 2025-07-05 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0008_alter_comment_author_alter_forumpost_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("guest_name", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to="forum.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_likes",
                        to="forum.forumpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forum_like",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("post__isnull", False), ("user__isnull", False)
                        ),
                        fields=("post", "user"),
                        name="unique_user_post_like",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("comment__isnull", False), ("user__isnull", False)
                        ),
                        fields=("comment", "user"),
                        name="unique_user_comment_like",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("guest_identifier__isnull", False), ("post__isnull", False)
                        ),
                        fields=("post", "guest_identifier"),
                        name="unique_guest_post_like",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("comment__isnull", False),
                            ("guest_identifier__isnull", False),
                        ),
                        fields=("comment", "guest_identifier"),
                        name="unique_guest_comment_like",
                    ),
                ],
            },
        ),
    ]
