# Generated by Django 5.1.6 on 2025-07-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0010_add_forum_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumpost",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
