# Generated by Django 5.1.6 on 2025-04-26 16:15

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # Add missing fields if they don't exist
            """
            DO $$
            BEGIN
                -- Add volume field if it doesn't exist
                IF NOT EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_name = 'research_researchpaper' AND column_name = 'volume'
                ) THEN
                    ALTER TABLE research_researchpaper ADD COLUMN volume character varying(50) NULL;
                END IF;
                
                -- Add issue field if it doesn't exist
                IF NOT EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_name = 'research_researchpaper' AND column_name = 'issue'
                ) THEN
                    ALTER TABLE research_researchpaper ADD COLUMN issue character varying(50) NULL;
                END IF;
                
                -- Add pages field if it doesn't exist
                IF NOT EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_name = 'research_researchpaper' AND column_name = 'pages'
                ) THEN
                    ALTER TABLE research_researchpaper ADD COLUMN pages character varying(50) NULL;
                END IF;
                
                -- Add download_url if it doesn't exist
                IF NOT EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_name = 'research_researchpaper' AND column_name = 'download_url'
                ) THEN
                    ALTER TABLE research_researchpaper ADD COLUMN download_url character varying(500) NULL;
                END IF;
                
                -- Copy data from url to download_url if both exist
                IF EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_name = 'research_researchpaper' AND column_name = 'url'
                ) AND EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_name = 'research_researchpaper' AND column_name = 'download_url'
                ) THEN
                    UPDATE research_researchpaper SET download_url = url WHERE download_url IS NULL;
                END IF;
            END $$;
            """,
            # No reverse SQL needed
            ""
        ),
        
        # Add Django ORM field definitions to match actual database changes
        migrations.AddField(
            model_name='researchpaper',
            name='volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='issue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='pages',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='download_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
