# Generated by Django 5.1.6 on 2025-04-30 17:14

import apps.utils.fields
from django.db import migrations, models
import os


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_initial'),  # CHANGE THIS to match an actual migration that exists in your directory
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='download_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='issue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='pages',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="researchpaper",
            name="publication_year",
            field=apps.utils.fields.YearField(verbose_name="Year"),
        ),
    ]
